openapi: 3.0.1
info:
  title: E-commerce API
  description: API for an e-commerce application
paths:
  /api/carts:
    get:
      summary: Get all carts
      tags:
        - Carts
      responses:
        '200':
          description: All carts found
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

  /api/carts/{id}:
    get:
      summary: Get one cart
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          description: cart id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cart found
        "401":
          description: Not authorized
        "500":
          description: Internal server error

    put:
      summary: Update Cart
      tags:
        - Carts
      parameters:
        - name: id
          in: path
          required: true
          description: cart id
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateCart'
         

    delete:
      summary: Delete cart by id
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: cid is the cart id which we want to delete
          schema:
            $type: string
      responses:
        "200":
          description: Cart deleted successfully
        "500":
          description: Internal server error

components:
  schemas:
    Carts:
      type: object
      properties:
        _id:
          type: string
          description: Cart id generated by the database
        title:
          type: string
          description: Cart title
        products:
          type: array
          description: Products in the cart
          items:
            type: object
            properties:
              id:
                type: string
                description: Product id
              quantity:
                type: number
                description: Quantity of the product in the cart
      example:
        _id: ahjg7862jahsgd871263
        title: Cart 1
        products:
          - id: product123
            quantity: 2
          - id: product456
            quantity: 1
  requestBodies:
    updateCart:
      type: object
      properties:
        _id:
          type: string
          description: Cart id generated by the database
        title:
          type: string
          description: Cart title
        products:
          type: array
          description: Products in the cart
          items:
            type: object
            properties:
              id:
                type: string
                description: Product id
              quantity:
                type: number
                description: Quantity of the product in the cart
      example:
        _id: ahjg7862jahsgd871263
        title: Cart 1
        products:
          - id: product123
            quantity: 2
          - id: product456
            quantity: 1